"""
Push the fine-tuned adapter and the IDRiD-VQA dataset to the Hugging Face Hub.

Token is read from the HF_TOKEN env var (never stored on disk). Run:
    HF_TOKEN=hf_xxx python scripts/hf_upload.py
Repo ids override via HF_MODEL_REPO / HF_DATASET_REPO.
"""
import io
import os
import sys
from pathlib import Path

from huggingface_hub import HfApi

ROOT = Path(__file__).resolve().parents[1]
ADAPTER = ROOT / "outputs" / "checkpoints" / "final"
VQA = ROOT / "data" / "processed" / "idrid_vqa.json"

USER = os.environ.get("HF_USER", "vermayuvraj")
MODEL_REPO = os.environ.get("HF_MODEL_REPO", f"{USER}/idrid-qwen2vl-2b-qlora")
DATASET_REPO = os.environ.get("HF_DATASET_REPO", f"{USER}/idrid-vqa")

MODEL_CARD = """---
license: cc-by-4.0
base_model: unsloth/Qwen2-VL-2B-Instruct
library_name: peft
pipeline_tag: image-text-to-text
tags:
- medical
- diabetic-retinopathy
- ophthalmology
- vision-language-model
- qlora
- unsloth
- lora
language:
- en
---

# IDRiD-DR-VLM: Qwen2-VL-2B + QLoRA for Explainable Diabetic Retinopathy Grading

A LoRA adapter for `Qwen2-VL-2B-Instruct` that grades diabetic retinopathy (0-4)
**and** produces a structured clinical explanation (grade, lesions, reasoning,
recommendation). Fine-tuned with 4-bit QLoRA (Unsloth) on the
[IDRiD-VQA](https://huggingface.co/datasets/{dataset_repo}) dataset, entirely on a
single 6 GB consumer GPU (NVIDIA RTX 4050).

> ⚠️ **Research use only. Not a medical device. Not for clinical use.**

## Results (103-image IDRiD test split)

| Model | Accuracy | QWK | ROUGE-L | BERTScore | s/img |
|---|---|---|---|---|---|
| Qwen2-VL-2B (zero-shot) | 31.1% | 0.00 | 0.081 | 0.000 | 10.6 |
| **+ QLoRA (this model)** | **66.0%** | **0.76** | **0.253** | **0.309** | **5.6** |

Fine-tuning lifts quadratic weighted kappa (the standard DR metric) from *no
agreement* to *substantial agreement* (0.76), ~3x better explanations, and ~2x
faster. Input resolution (768 px) was the biggest single lever.

## Usage
```python
from unsloth import FastVisionModel
from PIL import Image

model, tok = FastVisionModel.from_pretrained("{model_repo}", load_in_4bit=True)
FastVisionModel.for_inference(model)

img = Image.open("fundus.jpg").convert("RGB")
q = "What is the diabetic retinopathy severity grade (0-4) shown in this fundus image?"
msgs = [{{"role": "user", "content": [{{"type": "image"}}, {{"type": "text", "text": q}}]}}]
text = tok.apply_chat_template(msgs, add_generation_prompt=True)
inputs = tok(img, text, add_special_tokens=False, return_tensors="pt").to("cuda")
out = model.generate(**inputs, max_new_tokens=256, do_sample=False)
print(tok.decode(out[0][inputs["input_ids"].shape[1]:], skip_special_tokens=True))
```

## Training
QLoRA r=16, alpha=16 on all attention + MLP projections (language + vision towers),
batch size 1 x grad-accum 8, max_seq_length=1280, images at 768 px, bf16, 4 epochs.
Full run: ~90 min, peak 3.52 GB VRAM on a 6 GB RTX 4050.

## Limitations
Trained/evaluated on IDRiD only (single-centre, 516 images). Proliferative DR
(grade 4) is the hardest class because lesion flags derive from grade-conditioned
priors. Grade and reasoning come from separate generations and can occasionally
disagree. See the paper for details.

## Citation
```bibtex
@misc{{verma2026idridvqa,
  title  = {{IDRiD-VQA: Fine-Tuning a 2B Vision-Language Model for Explainable
            Diabetic Retinopathy Grading on Consumer Hardware}},
  author = {{Verma, Yuvraj}},
  year   = {{2026}}
}}
```
Built on IDRiD (Porwal et al., 2018, CC BY 4.0).
""".format(model_repo=MODEL_REPO, dataset_repo=DATASET_REPO)

DATASET_CARD = """---
license: cc-by-4.0
task_categories:
- visual-question-answering
- image-text-to-text
language:
- en
tags:
- medical
- diabetic-retinopathy
- ophthalmology
- fundus
size_categories:
- 1K<n<10K
---

# IDRiD-VQA

A visual-question-answering dataset for **explainable diabetic retinopathy grading**,
built from the [IDRiD](https://ieee-dataport.org/open-access/indian-diabetic-retinopathy-image-dataset-idrid)
Disease-Grading subset (516 fundus images). **2,064 QA pairs** (four per image),
generated by Gemini flash models from expert grade + lesion labels (not pixels), so
every answer is consistent with ground truth.

Each image has four QA types: **grade identification, lesion identification, clinical
reasoning, patient recommendation.**

## Fields
- `image`: relative path to the IDRiD fundus image (see below)
- `image_id`, `grade` (0-4), `split` (train/test), `qa_type`, `qa_source`
- `conversations`: `[{"role":"user","content":"<image>\\n<question>"}, {"role":"assistant","content":"<answer>"}]`

## Splits
Canonical IDRiD split: **413 train / 103 test images** (1,652 / 412 QA pairs). Train
and test reuse filenames, so the split is tracked by folder.

## Images
This dataset contains the **QA text only**. Download the fundus images from IDRiD
(free, CC BY 4.0) and place them at `data/raw/images/{train,test}/` to match the
`image` paths. This keeps the release light and respects IDRiD's distribution terms.

## Limitations
Answers are label-conditioned (bounding explanation diversity); lesion flags for the
grading set come from grade-conditioned clinical priors, not per-image masks.

## Citation
IDRiD: Porwal et al., *Data* 3(3):25, 2018 (CC BY 4.0). Please cite IDRiD and this
dataset. Not for clinical use.
"""


def main() -> int:
    token = os.environ.get("HF_TOKEN")
    if not token:
        print("[error] HF_TOKEN env var not set")
        return 1
    if not ADAPTER.exists() or not VQA.exists():
        print(f"[error] missing {ADAPTER} or {VQA}")
        return 1
    api = HfApi(token=token)
    who = api.whoami()
    print(f"[hf] authenticated as {who.get('name')}")

    # --- model repo ---
    print(f"[hf] creating model repo {MODEL_REPO}")
    api.create_repo(MODEL_REPO, repo_type="model", exist_ok=True, private=False)
    print("[hf] uploading adapter folder ...")
    api.upload_folder(folder_path=str(ADAPTER), repo_id=MODEL_REPO, repo_type="model",
                      commit_message="Add QLoRA adapter for IDRiD DR grading")
    api.upload_file(path_or_fileobj=io.BytesIO(MODEL_CARD.encode()), path_in_repo="README.md",
                    repo_id=MODEL_REPO, repo_type="model", commit_message="Add model card")
    print(f"[hf] MODEL -> https://huggingface.co/{MODEL_REPO}")

    # --- dataset repo ---
    print(f"[hf] creating dataset repo {DATASET_REPO}")
    api.create_repo(DATASET_REPO, repo_type="dataset", exist_ok=True, private=False)
    api.upload_file(path_or_fileobj=str(VQA), path_in_repo="idrid_vqa.json",
                    repo_id=DATASET_REPO, repo_type="dataset",
                    commit_message="Add IDRiD-VQA QA pairs")
    api.upload_file(path_or_fileobj=io.BytesIO(DATASET_CARD.encode()), path_in_repo="README.md",
                    repo_id=DATASET_REPO, repo_type="dataset", commit_message="Add dataset card")
    print(f"[hf] DATASET -> https://huggingface.co/datasets/{DATASET_REPO}")
    print("HF_UPLOAD_OK")
    return 0


if __name__ == "__main__":
    sys.exit(main())
