"""
Phase 6 — Gradio demo: "DR-VLM: Explainable Diabetic Retinopathy Analysis".

Fully offline (no API calls at inference). Loads the fine-tuned QLoRA adapter,
takes a fundus image, and returns a structured clinical report:
    grade -> lesions -> reasoning -> recommendation, plus inference time.

Run (inside WSL, venv active):
    python src/demo.py                       # launches on http://localhost:7860
    python src/demo.py --share               # public gradio link
"""
from __future__ import annotations

import os
# torch.compile/inductor needs a system C compiler (absent in this WSL); disable it.
os.environ.setdefault("TORCHDYNAMO_DISABLE", "1")
os.environ.setdefault("UNSLOTH_COMPILE_DISABLE", "1")

from unsloth import FastVisionModel  # noqa: E402

import argparse
import json
import time
from pathlib import Path

import gradio as gr
import torch
from PIL import Image

PROJECT_ROOT = Path(__file__).resolve().parents[1]
ADAPTER = PROJECT_ROOT / "outputs" / "checkpoints" / "final"
BASE_MODEL = "unsloth/Qwen2-VL-2B-Instruct"
MANIFEST = PROJECT_ROOT / "data" / "processed" / "idrid_manifest.json"
IMAGE_MAX_SIDE = 512

DISCLAIMER = "⚠️ **Research purposes only. Not for clinical use.**"

SECTIONS = [
    ("Grade", "What is the diabetic retinopathy severity grade (0-4) shown in this "
              "fundus image? Answer with the number and its name."),
    ("Lesions", "Which diabetic retinopathy lesions are visible in this fundus image?"),
    ("Clinical reasoning",
     "Explain the clinical reasoning that supports this diabetic retinopathy grade."),
    ("Recommendation",
     "Based on this fundus image, what follow-up and management would you recommend?"),
]

_MODEL = None
_TOK = None


def _load_model():
    global _MODEL, _TOK
    if _MODEL is not None:
        return
    ref = str(ADAPTER) if ADAPTER.exists() else BASE_MODEL
    if not ADAPTER.exists():
        print(f"[warn] adapter not found at {ADAPTER}; loading BASE model {BASE_MODEL}")
    _MODEL, _TOK = FastVisionModel.from_pretrained(ref, load_in_4bit=True)
    FastVisionModel.for_inference(_MODEL)


def _prep(image: Image.Image) -> Image.Image:
    image = image.convert("RGB")
    w, h = image.size
    if max(w, h) > IMAGE_MAX_SIDE:
        s = IMAGE_MAX_SIDE / max(w, h)
        image = image.resize((int(w * s), int(h * s)), Image.BILINEAR)
    return image


def _ask(image: Image.Image, question: str) -> str:
    messages = [{"role": "user", "content": [
        {"type": "image"}, {"type": "text", "text": question}]}]
    input_text = _TOK.apply_chat_template(messages, add_generation_prompt=True)
    inputs = _TOK(image, input_text, add_special_tokens=False,
                  return_tensors="pt").to("cuda")
    with torch.inference_mode():
        out = _MODEL.generate(**inputs, max_new_tokens=256, use_cache=True,
                              do_sample=False)
    return _TOK.decode(out[0][inputs["input_ids"].shape[1]:],
                       skip_special_tokens=True).strip()


def analyze(image):
    if image is None:
        return "Please upload a fundus image."
    _load_model()
    img = _prep(image)
    t0 = time.time()
    parts = [f"# Diabetic Retinopathy Report\n", DISCLAIMER, ""]
    for title, q in SECTIONS:
        parts.append(f"### {title}\n{_ask(img, q)}\n")
    dt = time.time() - t0
    parts.append(f"---\n*Inference time: {dt:.2f} s on local GPU (fully offline).*")
    return "\n".join(parts)


def _examples() -> list[str]:
    """5 preloaded test images (prefer test split from the manifest)."""
    paths: list[str] = []
    if MANIFEST.exists():
        recs = [r for r in json.loads(MANIFEST.read_text()) if r.get("split") == "test"]
        for r in recs[:5]:
            p = PROJECT_ROOT / r["image"]
            if p.exists():
                paths.append(str(p))
    if not paths:
        img_dir = PROJECT_ROOT / "data" / "raw" / "images"
        if img_dir.exists():
            paths = [str(p) for p in sorted(img_dir.glob("*.jpg"))[-5:]]
    return paths


def build_ui() -> gr.Blocks:
    with gr.Blocks(title="DR-VLM: Explainable Diabetic Retinopathy Analysis") as demo:
        gr.Markdown("# DR-VLM: Explainable Diabetic Retinopathy Analysis")
        gr.Markdown(
            "Upload a retinal fundus image to receive a structured clinical report "
            "(grade, lesions, reasoning, recommendation), generated by a fine-tuned "
            "Qwen2-VL-2B model running **fully offline**.\n\n" + DISCLAIMER)
        with gr.Row():
            with gr.Column():
                inp = gr.Image(type="pil", label="Fundus image")
                btn = gr.Button("Analyze", variant="primary")
                ex = _examples()
                if ex:
                    gr.Examples(examples=ex, inputs=inp, label="Example test images")
            out = gr.Markdown(label="Clinical report")
        btn.click(analyze, inputs=inp, outputs=out)
    return demo


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--share", action="store_true")
    ap.add_argument("--port", type=int, default=7860)
    args = ap.parse_args()
    build_ui().launch(server_name="0.0.0.0", server_port=args.port, share=args.share)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
