r"""
Auto-generate the experiments table (paper/results_table.tex) from
outputs/evaluation_results.json. Run after evaluation:

    python paper/make_table.py

main.tex \input{results_table.tex}, so recompiling the paper picks up new numbers.
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RESULTS = ROOT / "outputs" / "evaluation_results.json"
OUT = Path(__file__).resolve().parent / "results_table.tex"

PRETTY = {
    "base_qwen2vl_2b": "Qwen2-VL-2B (zero-shot)",
    "finetuned_qlora": "Qwen2-VL-2B + QLoRA (ours)",
    "gpt_4o_mini": "GPT-4o-mini (zero-shot)",
}
ORDER = ["base_qwen2vl_2b", "gpt_4o_mini", "finetuned_qlora"]


def _fmt(v, pct=False):
    if v is None:
        return "--"
    if pct:
        return f"{100 * v:.1f}"
    return f"{v:.3f}"


def build(results: dict) -> str:
    rows = []
    for key in ORDER:
        if key not in results:
            continue
        m = results[key]["metrics"]
        name = PRETTY.get(key, key)
        if key == "finetuned_qlora":
            name = r"\textbf{" + name + "}"
        rows.append(
            f"{name} & {_fmt(m.get('accuracy'), pct=True)} & "
            f"{_fmt(m.get('qwk'))} & {_fmt(m.get('rougeL'))} & "
            f"{_fmt(m.get('bertscore_f1'))} & "
            f"{_fmt(m.get('sec_per_image'))} & "
            f"{('%.5f' % m['cost_per_image_usd']) if m.get('cost_per_image_usd') is not None else '--'} \\\\"
        )
    body = "\n".join(rows) if rows else "\\multicolumn{7}{c}{(run src/evaluate.py to populate)} \\\\"
    return TEMPLATE.format(body=body)


TEMPLATE = r"""% Auto-generated by paper/make_table.py — do not edit by hand.
\begin{{table*}}[t]
\centering
\small
\begin{{tabular}}{{lcccccc}}
\toprule
\textbf{{Model}} & \textbf{{Acc.}} & \textbf{{QWK}} & \textbf{{ROUGE-L}} & \textbf{{BERTScore}} & \textbf{{s/img}} & \textbf{{\$/img}} \\
\midrule
{body}
\bottomrule
\end{{tabular}}
\caption{{DR grading and explanation quality on the 103-image IDRiD test split.
Accuracy is exact-match over grades 0--4; QWK is quadratic weighted kappa;
ROUGE-L and BERTScore measure explanation quality against the reference
clinical reasoning. \emph{{s/img}} and \emph{{\$/img}} are mean inference latency
and marginal API cost per image (local models incur no per-call cost).}}
\label{{tab:results}}
\end{{table*}}
"""


def main() -> int:
    if RESULTS.exists():
        results = json.loads(RESULTS.read_text())
    else:
        print(f"[warn] {RESULTS} not found — emitting placeholder table")
        results = {}
    OUT.write_text(build(results))
    print(f"[ok] wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
